<?php

declare(strict_types=1);

namespace Zenstruck\Foundry\Tests\Integration\InMemory;

use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;
use Zenstruck\Foundry\Tests\Fixture\Entity\Address\StandardAddress;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\StandardAddressFactory;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Contact\StandardContactFactory;
use Zenstruck\Foundry\Tests\Fixture\InMemory\InMemoryStandardAddressRepository;
use Zenstruck\Foundry\Tests\Fixture\InMemory\InMemoryStandardContactRepository;
use function Zenstruck\Foundry\InMemory\enable_in_memory;

final class InMemoryTest extends KernelTestCase
{
    use Factories;
    use ResetDatabase;

    private InMemoryStandardAddressRepository $addressRepository;
    private InMemoryStandardContactRepository $contactRepository;
    private EntityManagerInterface $entityManager;

    protected function setUp(): void
    {
        enable_in_memory();

        $this->addressRepository = self::getContainer()->get(InMemoryStandardAddressRepository::class);
        $this->contactRepository = self::getContainer()->get(InMemoryStandardContactRepository::class);

        $this->entityManager = self::getContainer()->get(EntityManagerInterface::class);
    }

    /**
     * @test
     */
    public function create_one_does_not_persist_in_database(): void
    {
        $address = StandardAddressFactory::createOne();
        self::assertInstanceOf(StandardAddress::class, $address);

        $this->assertDatabaseIsEmpty(StandardAddress::class);

        // id is autogenerated from the db, then it should be null
        self::assertNull($address->id);
    }

    /**
     * @test
     */
    public function create_many_does_not_persist_in_database(): void
    {
        $addresses = StandardAddressFactory::createMany(2);
        self::assertContainsOnlyInstancesOf(StandardAddress::class, $addresses);

        $this->assertDatabaseIsEmpty(StandardAddress::class);

        self::assertCount(2, $addresses);
        foreach ($addresses as $address) {
            // id is autogenerated from the db, then it should be null
            self::assertNull($address->id);
        }
    }

    /**
     * @test
     */
    public function object_should_be_accessible_from_in_memory_repository(): void
    {
        $address = StandardAddressFactory::createOne();

        self::assertSame([$address], $this->addressRepository->_all());
    }

    /**
     * @test
     */
    public function nested_objects_should_be_accessible_from_their_respective_repository(): void
    {
        $contact = StandardContactFactory::createOne();

        self::assertSame([$contact], $this->contactRepository->_all());
        self::assertSame([$contact->getAddress()], $this->addressRepository->_all());
    }

    private function assertDatabaseIsEmpty(string $entityClass): void
    {
        self::assertSame(
            0,
            $this->entityManager->getRepository($entityClass)->count([])
        );
    }
}
